# MongoDB local connection
spring.data.mongodb.uri=mongodb://localhost:27017/freshflow_db

# Run on Port 8080
server.port=8080

# Show MongoDB logs for testing
logging.level.org.springframework.data.mongodb=DEBUG